### ISSUE TITLE
Paginate "Profile Creation" view

### ISSUE THREAD

**Issue by cxrodgers** [safwanrahman/jobtalk_beta#7]
When a new user creates a profile, the info should be solicited in three separate pages:

Page 1:
- username
- current institution
- position
- field of research
- more about your field of research
- work email

Page 2:
- what is your vision
- what is your ideal workplace
- I'm interested in .. (dropdown)

Page 3:
- Gender
- Ethnicity

**Comment by cxrodgers** [comment]
I think this might be what we need:
https://docs.djangoproject.com/en/1.7/ref/contrib/formtools/form-wizard/

**Comment by cxrodgers** [comment]
I have a simple version of this that uses the form-wizard tools on this branch:
https://github.com/cxrodgers/jobtalk_beta/tree/paginate_user_form

However I can't get the template to work with the bootstrap template, so it just looks like the django defaults (ugly). 
https://github.com/cxrodgers/jobtalk_beta/blob/paginate_user_form/core/templates/formtools/wizard/wizard_form.html

Anyone know how to fix this?

**Comment by safwanrahman** [comment]
I was thinking about using ``django-rest-framework` to build API then create the three page frontend with react or something like that. But I do not have much knowledge in javascript, so its over challenged for me.

**Comment by cxrodgers** [comment]
Yeah I'm not that comfortable with this part either. I did figure out how to do a simple pagination and keep the bootstrap template though. Will make a few more edits to make it match the mockup.pdf and then submit a PR
